### ISSUE TITLE
I can not see if the loudness plugin is executed.

### ISSUE THREAD

**Issue by riana68** [dpapavas/alsaloudness#1]
I introduce some debug print in the loundness code and I execute aplay command. but I doesn't see debug print on the command line. dat means that loundness plugin is not executed. please, could you tell me if this the right method to test your plugin?

**Comment by dpapavas** [comment]
You can see debug output of the plugin itself by compiling it via something like: `make DEBUG=yes && sudo make install`.  After that, it should emit output when using `aplay` on the console.  Note also, that you can use `aplay` with the `-v` switch, in order to see the overall plugin chain, which should list `alsaloudness`, if all is configured properly.  If not, it might give you a clue as to what's wrong.
