### ISSUE TITLE
Hissing noise introduced, when using alsaloudness after equalization

### ISSUE THREAD

**Issue by arturohernandez10** [dpapavas/alsaloudness#13]
I have setup a music server using mopidy, a raspberry 3B, and sending the audio to alsa. I used REW to make an equalization pipe in alsa, which works really well. After some testing I got alsaloudness installed and working. Using the asound.conf file attached here. It works really well except that there is a perceptible noise. I'm not a signal processing expert, but I was afraid that an FFT could do that. 

I am passing the input throught the equalizer first. Could I have done something wrong? I'm more than happy to send sample sound recordings if that helps. Or even just a couple of pointers would be useful.

I never realized that I needed this to hear low volume music. And I really like it.
[asound.conf.txt](https://github.com/dpapavas/alsaloudness/files/7248175/asound.conf.txt)

Thanks

**Comment by arturohernandez10** [comment]
I need to do more research. If this is still an issue I'll reopen.

**Comment by dpapavas** [comment]
One thing I can tell you, is that the loudness compensation carried out by `alsaloudness` is essentially done via boosting of the bass and treble content and this boosting intensified as the attenuation goes up (or down in terms of negative dB - see the curves published in the README).  So, although it might well be conceivable, that the filtering done by `alsaloudness` introduces the hissing artifact, it is also likely that it either makes a hiss in the source material more pronounced (I haven't noticed anything of the kind with any of the material I listen to), or that the boosted content causes the equalization plugin (which you seem to have placed downstream of `alsaloudness`) to misbehave, producing the hiss.

This suggests a few things to try:
1. Temporarily remove the REW plugin, to take it out of the picture and see if the hiss is still there.
2. Try different source material, preferably from different labels and genres, trying to find if the hiss is (at least in part) due to the material, or not.
3. Try to reverse the order of chaining, so that `alsaloudness` is at the end, right before the HW PCM.
4. Try different equalization plugins.
