### ISSUE TITLE
Compiling on Raspberry Pi Zero ?

### ISSUE THREAD

**Issue by Wikinaut** [dpapavas/alsaloudness#15]
Compiling on Raspberry Pi Zero with armv6 (debian 11 bullseye) needs – as far as I understand – apparently `make LIB32=yes`, but then the cc throws this error message 

```
cc: error: unrecognized command-line option ‘-m32’; did you mean ‘-mbe32’?
```

**Comment by dpapavas** [comment]
I haven't had any experience with Pi Zero, but on the Pi 3B I have used `alsaloudness` on, setting `LIB32` wasn't necessary.  In fact I don't know when it would be necessary (it was a contributed Makefile change), as it's meant to compile a 32-bit library on an otherwise 64-bit system.  I suppose it's meant to be used with 32-bit applications using ALSA on 64-bit systems.  Why do you think you need it?

(As regards the problem itself, it's due to the fact that the `LIB32` switch seems to only support Intel architectures. The `-m32` switch isn't supported on Arm machines.)

**Comment by Wikinaut** [comment]
I was simply unsure, as there are several texts on the Internet saying that most of the software on (even 64-bit) Raspberries is still only 32-bit software.

I could `make` the loudness module but I was unsure how to set up `attenuation`  and `reference`. I cannot reproduce the same level - with or withour your module - at the moment. Perhaps you could explain better what the two sliders (in alsamixer) actually do. I read something in your fine documentation, but it was not clear to me.

The audio output currently sounds dull and not so loud as without your module. I am working on a pinetradio https://github.com/Wikinaut/pinetradio and would like to use your module therein.

**Comment by Wikinaut** [comment]
@dpapavas Dimitri, in case you have it running on your Raspberry, please can you let me know your settings for `attenuation` and `reference`?

**Comment by dpapavas** [comment]
If you can build and use it without setting `LIB32`, then you don't need it.  As for the settings, you can leave `reference` to the default 82dB;  I haven't found much use in fiddling with it, although you can try once you get the basics right.  Then set `attenuation` to something like 50% initially and set the "real" volume controls of the sound card to 100% (making sure that all relevant controls that may exist (master, PCM, etc.), are set to 100%.  You can then adjust the final volume through the `attenuation` control.  If you find the sound to be too bass-heavy and boomy, try dialing down the card's "real" volume.

I usually set `reference` to 82dB, "real" volume to between -6 and -3 dB, or so and `attenuation` depending on time of day, mood and material, that is depending on desired playback volume.

**Comment by Wikinaut** [comment]
hmmm, I need to control the volume programmatically in Python; see my pinetradio code, in mplayer slave mode by sending `volume xx 1` (xx = 0...100) to mplayer. Perhaps I lack something in understanding. I thought, that your module is adding `loudness` like in "old" amplifiers. When I add you module, the overall amplitude appears to be 50% or so less than without your module (standard settings of your code), and the sound is "dull".

So you want me to set the real volume to -6 or -3 db (~full) and to control the volume via `attenuation`, but then my question is how can I do this with Python?


Any help is welcomed!
https://github.com/Wikinaut/pinetradio/blob/main/pinetradio.py

.... [ "Ellinikos 93,2", "http://netradio.live24.gr/orange9320" ],

**Comment by dpapavas** [comment]
`alsaloudess` does indeed implement something like the "loudness" button in old amplifiers, but id does it by attenuating the volume through equalization, in a loudness-compensated manner.  It can't just see what volume you've set your card at and do loudness compensation after the fact and independent of that.  Instead it assumes you've set your normal card's volume to 100%, or close to that (see discussion above and README) and then reduces(attenuates) that volume based on the setting of the `Attenuation` control, making sure that bass and treble content gets attenuated less, so that the perceived volume remains constant across the spectrum.  This makes the `Attenuation` control your volume knob.

I haven't tried controlling ALSA devices through Python, but two options that come to mind are using `os.system` or the `subprocess` module to call the `amixer` utility to set the volume, or using some module to talk to ALSA, such as ([this](https://github.com/larsimmisch/pyalsaaudio/blob/main/mixertest.py)).
