### ISSUE TITLE
tiny core

### ISSUE THREAD

**Issue by roresrores** [dpapavas/alsaloudness#2]
Hello, i try to install alsaloudness on a picoreplayer, this is an tiny core linux. now i get the following error when i use the command make:
tc@garten:~/alsaloudness-master$ make
cc -o libasound_module_pcm_loudness.so -shared -fPIC -DPIC -Wall -Wextra -Wpedantic -O3 -DNDEBUG loudness_pcm.c -lm -lasound -lfftw3f
loudness_pcm.c: In function 'configure_card_ctl':
loudness_pcm.c:809:13: warning: implicit declaration of function 'SNDRV_CTL_TLVD_DECLARE_DB_MINMAX'; did you mean 'SNDRV_CTL_TLVT_DB_MINMAX'? [-Wimplicit-function-declaration]
             SNDRV_CTL_TLVD_DECLARE_DB_MINMAX(tlv,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             SNDRV_CTL_TLVT_DB_MINMAX
loudness_pcm.c:809:46: error: 'tlv' undeclared (first use in this function)
             SNDRV_CTL_TLVD_DECLARE_DB_MINMAX(tlv,
                                              ^~~
loudness_pcm.c:809:46: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:37: libasound_module_pcm_loudness.so] Error 1
tc@garten:~/alsaloudness-master$

im sorry, im new with linux, i dont know how to solve this problem.
thx for you help, wbr Roland

**Comment by dpapavas** [comment]
I'm not sure how to interpret the fact that your `make` output above is strike-through; I'll assume it's still relevant.  That output suggests that the compiler can't find information needed to build the program which is usually due to the fact that certain development packages, containing so-caller header files and other stuff haven't been installed.  The curious thing is that here, the compiler does seem to find the needed header file, but it seems to be missing certain parts.

I'm not familiar with Tiny Core Linux, but there's a package called `alsa-dev` that contains development files for ALSA, which should include the header file you seem to be missing.  Have you installed that?

**Comment by roresrores** [comment]
I have the plugin now installed on raspian stretch and it works there easily. One question I still have, does the effect changes dynamically with the change of the volume (Master)?
I mean, if the volume on the player is set to low, is the loudness correction higher than if I set the volume on the player aloud?

**Comment by dpapavas** [comment]
No, the filter does not track the card's master volume, but, as explained in the README,  it does adapt compensation dynamically to its own `Attenuation` control.  The idea is that you'll set the master volume to a certain value and then adjust listening volume via the `Attenuation` control, without loss of bass and treble (in theory).  I explain the theory of operation and use in the README, but, in practice, you can think of the two controls like this:

When you lower the volume via `Attenuation` the bass and treble is boosted, in order to preserve the level heard by the ear.  Conversely, when you raise the volume via `Attenuation`, the bass and treble boost is reduced.  You shouldn't notice these changes in boost, since they're meant to compensate for the way your ear works, but when you adjust the volume via the card's normal master control, the volume changes without any change in boost.  Therefore, adjusting volume via the master control is effectively like adjusting the boost, or the intensity of the compensation.  Raising the volume via master increases bass and treble content and lowering volume via master diminishes it (which is exactly the problem loudness compensation is supposed to counter, after all).

So the idea is that you set the master volume to get the overall sound you prefer (for instance, if it's thin you raise it, if it's boomy you lower it) and then adjust you listening volume through `Attenuation` with (hopefully) no change in the equalization.  In practice, for my setup and the music I listen to, I've found that setting the master volume to about -6dB to -8dB or so works most of the time.  Then I can forget about it and use `Attenuation` as my volume control.

**Comment by roresrores** [comment]
Thanks for the explanations. I asked for that because I use squeezelite as a player and this has its own volume control, not via ALSA. Although I can start squeezelite with “-Dloudness” and so I can set in the alsamixer already the Attenuation, but that is then unfortunately statically set
This Is really a Great plugin but unfortunately it is not usable for me like that ☹

**Comment by dpapavas** [comment]
You can still use it, but you'll have to forgo the hardware volume control.  You can set the hardware volume knob to the maximum volume you're likely to need and leave it there, then proceed as explained above.  (That is effectively how I use it too, since I use a power amplifier without a volume knob which is like one with a volume knob stuck to the maximum setting.)
