### ISSUE TITLE
Loudness usage via mpd

### ISSUE THREAD

**Issue by maziggy** [dpapavas/alsaloudness#4]
Hi,

I'm using Volumio and would like to use the alsaloudness plugin. To be honest I'm not that familiar with the ALSA stuff. So maybe I'm just missing something.

# /etc/asound.conf

`pcm_type.loudness {
    lib "/usr/lib/libasound_module_pcm_loudness.so"
}

pcm.plugloudness {
    type loudness
    reference 82
    attenuation -20
    controls {
        install yes
    }
    slave.pcm "plughw:1,0"
}

pcm.loudness{
    type plug
    slave.pcm "plugloudness"
}
`

# /etc/mpd.conf
`[...]
audio_output {
                type            "alsa"
                name            "alsa"
                device          "plug:loudness"
}
[...]
`

Unfortunately I always get the error message "Failed to open ALSA device "plug:loudness": invalid argument.

Any help is appreciated!

Thanks, Martin

**Comment by dpapavas** [comment]
Your problem is probably that `pcm.loudness` is already a plug PCM and specifying `plug:loudness` means "use the PCM `loudness` through a plug" so now you have two plugs in series.

In any case though, before tackling setting up MPD, make sure you can play a simple file, as suggested in the Readme: `# aplay -Dloudness /path/to/some.wav`

**Comment by carstenbusch** [comment]
Hi,

I played around with your Plugin and I'm really happy with it! I'm running a raspberry pi3b with Squeezebox with an equalizer as Alsa-Plugin. On top of that there's your Loudness-Plugin optimizing the Sound specially for lower volumes.

Beeing able to adjust Attenuation instead of a "plain volume"-mixer allows a great sound at almost all volumes my amp/speakers allow. The only thing I'm struggeling with are some very loud crack's (almost like a shot) when playing Sound through the Loudness-Plugin. Seems to depend on the CPU-Usage the Plugin consumes. I played around with the amount of treads, window- and fft-size but that is changing the CPU-Usage within 43% and 48%: the crack's still come up.

Even if I set on the Plugin without the 2nd-Plugin "Equalizer" it doesn't change a lot.

This is the current configuration:
/etc/asound.conf

```
#ctl.!default {
#    type hw
#    card 0
#}
pcm.equal {
    type plug;
    slave.pcm plugequal;
}
ctl.equal {
   type equal;
   module "Eq10";
}

pcm.plugequal {
   type equal;
   module "Eq10";
   slave {
     pcm "plughw:0,0";
   }
   hint {show on;description "Equalizer for plughw:0,0"}
}


pcm_type.loudness {
    lib "/usr/local/lib/libasound_module_pcm_loudness.so"
}


# This defines the plugin's configuration.  See the README file for
# more information on the various parameters.

pcm.plugloudness {
    type loudness

    #threads 4
    #window 4096
    #fft 16384

    reference 82
    # Original: attenuation -20
    attenuation -36

    controls {

        install yes

        # prefix "My "
    }

    # Edit the line below to specify the card and device to play
    # through, if necessary.

    # Original: slave.pcm "plughw:0,0"
    slave.pcm "plugequal"
    #slave.pcm "plughw:0,0"
        hint {show on;description "Loudness-Plugin"}
}

# alsaloudness does all processing in floating point, so a plug PCM is
# necessary to handle the necessary conversion on both the input and
# output side.  (This is also the reason for specifying plughw above.)

pcm.loudness{
    type plug

    slave {
          pcm plugloudness
    }
}


#########################
# Standard-Ausgabe
#
#########################

pcm.!default {
    type plug
    slave.pcm "plugloudness"
}
```

Do you have any recommendations? Changing to a raspberry 4 brings better performance, but you didn't have that performance while developing that plugin one year ago...

Thanks a lot, Carsten
