### ISSUE TITLE
High CPU-Usage causing Cracks while playing

### ISSUE THREAD

**Issue by carstenbusch** [dpapavas/alsaloudness#5]
Hi,

I played around with your Plugin and I'm really happy with it! I'm running a raspberry pi3b with Squeezebox with an equalizer as Alsa-Plugin. On top of that there's your Loudness-Plugin optimizing the Sound specially for lower volumes.

Beeing able to adjust Attenuation instead of a "plain volume"-mixer allows a great sound at almost all volumes my amp/speakers allow. The only thing I'm struggeling with are some very loud crack's (almost like a shot) when playing Sound through the Loudness-Plugin. Seems to depend on the CPU-Usage the Plugin consumes. I played around with the amount of treads, window- and fft-size but that is changing the CPU-Usage within 43% and 48%: the crack's still come up.

Even if I set on the Plugin without the 2nd-Plugin "Equalizer" it doesn't change a lot.

This is the current configuration:
/etc/asound.conf

```
#ctl.!default {
#    type hw
#    card 0
#}
pcm.equal {
    type plug;
    slave.pcm plugequal;
}
ctl.equal {
   type equal;
   module "Eq10";
}

pcm.plugequal {
   type equal;
   module "Eq10";
   slave {
     pcm "plughw:0,0";
   }
   hint {show on;description "Equalizer for plughw:0,0"}
}


pcm_type.loudness {
    lib "/usr/local/lib/libasound_module_pcm_loudness.so"
}


# This defines the plugin's configuration.  See the README file for
# more information on the various parameters.

pcm.plugloudness {
    type loudness

    #threads 4
    #window 4096
    #fft 16384

    reference 82
    # Original: attenuation -20
    attenuation -36

    controls {

        install yes

        # prefix "My "
    }

    # Edit the line below to specify the card and device to play
    # through, if necessary.

    # Original: slave.pcm "plughw:0,0"
    slave.pcm "plugequal"
    #slave.pcm "plughw:0,0"
        hint {show on;description "Loudness-Plugin"}
}

# alsaloudness does all processing in floating point, so a plug PCM is
# necessary to handle the necessary conversion on both the input and
# output side.  (This is also the reason for specifying plughw above.)

pcm.loudness{
    type plug

    slave {
          pcm plugloudness
    }
}


#########################
# Standard-Ausgabe
#
#########################

pcm.!default {
    type plug
    slave.pcm "plugloudness"
}
```

Do you have any recommendations? Changing to a raspberry 4 brings better performance, but you didn't have that performance while developing that plugin one year ago...

Thanks a lot, Carsten

**Comment by dpapavas** [comment]
I'm afraid that your problem is not related to CPU usage and not even directly to `alsaloudness`, although the latter exacerbates it indirectly.  My suspicion is that your card allows loud (in terms of sample volume) cracks to get through to the output, which normally, i.e. when you're not using `alsaloudness` and have your master volume set relatively low, sound like "normal" pops.  On the other hands, when playing via `alsaloudness` you have to set your master volume very high and these pops, which are not software-generated and hence are unaffected by your attenuation setting, sound out like a gunshot.

I've had similar issues, before `alsaloudness`, because my setup involves only a power amplifier, without a volume control, so that all attenuation is done in software, via the ALSA mixer.  What DAC are you using and what kernel version are you running?

**Comment by carstenbusch** [comment]
Hi,

thanks for your answer!

I'm on Raspian 9 Stretch, Linux 4.19.57-v7+ armv7l (max2play-Image) with a Hifiberry DAC+ pro and a pre-Amp in between the raspi and the power amplifier.

I didn't recognise any cracks when playing through the card or the equalizer-plugin without `alsaloudness`. When I'm playing through alsaloudness it is the same cracks when adjusting volume via "Master" or "Attenuation". Even when I' not changing Volume / don't touch anything the cracks appear: sometimes one / two within a few seconds, sometimes entire minutes without them.

**Comment by dpapavas** [comment]
The pops I have in mind happen under certain conditions, when the sound card is opened and/or the mode is switched between 16 and 24 bit.  Do you get pops in the middle of songs?  If so, assuming you're using MPD, can you look in the logs for any messages about underruns?

When you mute the `Attenuation` channel or set it to 0, `alsaloudness` just copies input to output and doesn't do any filtering.  This should lower its impact on CPU load considerably.  Can you see if that's the case and if so, whether you cease having pops then?  (You also won't have any loudness compensation of course, but it's only meant as a test, not as a solution.)

You might also want to run the script I posted [here](https://github.com/raspberrypi/linux/issues/2741#issue-377161494) (which you can do by pasting it into a file, say `pop.py` and running it via `python pop.py`.  You might also have to install the `python-alsaaudio` package.  Also note the caveat right after the script in the post and also note that the script should be run with the card idle, i.e. while playing nothing and without running `pulseaudio` or a similar daemon.)

I sincerely hope you won't get any pops (but turn down your external volume control to be safe), because otherwise it would mean that something didn't go as it should with the fix, which is the last thing I would need right now.

**Comment by carstenbusch** [comment]
Hi,

the pops came up in the middle of songs and even within songs beeing paused, so that there should be no switches of bitrates between 16 and 24 bit. I'm using Squeezelite on Max2Play as Client for Logitech Media Server.

The hint with the possible underruns gave me reason to test with the Alsa buffer. I thought that the buffer could only help with network problems or slow internet connection, but since then I have these pops much less often, they are almost gone.

Maybe there are still some underruns but less often: how could I log those?

Thanks a lot,
Carsten

**Comment by dpapavas** [comment]
>the pops came up in the middle of songs and even within songs beeing paused, so that there should be no switches of bitrates between 16 and 24 bit.

Getting pops "even while songs are paused" sounds very peculiar.  I'm not familiar with Max2Play or Squeezelite; perhaps it has some special behavior, e.g. keeping the card playing silence when paused.

>Maybe there are still some underruns but less often: how could I log those?

Well if your system is based on MPD, you may get error messages about underruns in MPD's log, located typically in `/var/log/mpd`.  If not, you might want to find and check the log files of your player.

It might also be a good idea to try to playing a song file directly on the command line, e.g. using `ffplay`, or converting to `wav` and using `aplay`.  If cracks continue with `aplay` and `wav`, this would indicate that the problem is unrelated to the palyback software, and even to the compression method.  It should also print underruns as error messages directly in the terminal.

What kind of audio files are you using?  Particularly, what is the compression used (flac, mp3, etc.) and what sort of sampling rate (e.g. 44.1, 48, or 96kHz) and sample format (e.g. 16 or 24 bit) do you typically use?

If, as I suspect, you use high resolution formats (i.e. 24/96 and stuff like that), can you try to find similar spec samples which are freely available online (e.g. [here](http://www.2l.no/hires/)) so that I can try to reproduce the problem at my end?  I don't much use high resolution material, so maybe that's why I haven't had problems.
