### ISSUE TITLE
Attenuator vs amixer cset

### ISSUE THREAD

**Issue by MortenAasted** [dpapavas/alsaloudness#6]
Hi sir
What is the relationship between the amixer pcm volume control and the new attenuation control?
I use an analogue input to adjust the volume by amixer commands. If i want to use the loudness would i then need to adress the attenuation control instead and leave the pcm volume at fixed level?
I assume the attenuation is still hardware control as the amixer?

Best
Morten

**Comment by dpapavas** [comment]
No the attenutation control is implemented in software.  As described in the Readme, the purpose of `alsaloudness`, is to attenuate the sound (i.e. lower the output volume) by as many dB, are set via the `Attenuation` control, with loudness compensation.  You're correct in assuming that you'll have to  leave the pcm volume at a fixed level, and set your listening volume via the `Attenuation` control (which you can do with `amixer` just fine).  See [here](https://github.com/dpapavas/alsaloudness#using-the-compensated-controls) for a possible strategy.

(As an example, with my setup i find that it works just fine to set the PCM to just shy of full scale, at -6dB, and set `Attenuation` according to mood and hour of day, but my system is relatively low-power, so you might have to set it lower.  A bit of experimentation should be sufficient to figure out proper settings.)

**Comment by MortenAasted** [comment]
Okay, wouldn't this kind of software volume degrade SQ? 🤔 
Best 
Morten

**Comment by dpapavas** [comment]
Well, if you consider equalization to degrade sound quality, perhaps (although there's certainly nothing intrinsically degrading about filtering in software).  Still there's no cause for alarm: you can try it out and see if you like it better with or without the compensation.  I've made it so that, when you mute the `Attenuation` channel, the sound is passed straight through (with simple software volume attenuation, so that the overall level is retained, but without compensation), just as if you had set the volume at the same level through the PCM control as usual.

You can bind that to your remote via `amixer` and instantly switch between "with" vs "without" alsaloudness, for easy (albeit non-blind) A/B testing.  You can use this to form an opinion about the result and to finetune your settings.
